name: Build RealFire Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter tk pillow requests pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile .\main.py --icon=assets\icons\firefox.ico --add-data "data\installer_data.json;data" --add-data "assets\icons;assets/icons" --add-data "assets\backgrounds;assets/backgrounds" --noconsole

      - name: Install Windows SDK
        run: |
          choco install windows-sdk-10.0 --confirm
        shell: powershell

      - name: Create self-signed certificate
        run: |
          openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=RealFire"
          openssl pkcs12 -export -out cert.pfx -inkey key.pem -in cert.pem -passout pass:password

      - name: Sign the executable
        run: |
          $env:PATH += ";C:\Program Files (x86)\Windows Kits\10\bin\x64"
          signtool sign /f cert.pfx /p password /fd SHA256 /tr http://timestamp.digicert.com /td SHA256 dist\main.exe
        shell: powershell

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v3
        with:
          name: RealFire-Installer-Windows
          path: dist\main.exe

      - name: Create GitHub Release - Windows
        id: create_release_windows
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NEWTOKEN }}
        with:
          tag_name: v1.0.0-windows
          release_name: RealFire Installer v1.0.0 - Windows
          body: |
            Release for Windows build of RealFire Installer v1.0.0.
          draft: false
          prerelease: false

      - name: Upload Release Asset - Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NEWTOKEN }}
        with:
          upload_url: ${{ steps.create_release_windows.outputs.upload_url }}
          asset_path: ./dist/main.exe
          asset_name: RealFire-Installer-Windows.exe
          asset_content_type: application/x-msdownload
