name: Dispatch Build Jobs

on:
  workflow_dispatch:
    inputs:
      build-for-windows:
        description: 'Build for Windows'
        required: false
        default: 'false'
      build-for-linux:
        description: 'Build for Linux'
        required: false
        default: 'false'
      build-for-macos:
        description: 'Build for macOS'
        required: false
        default: 'false'
      build-for-all:
        description: 'Build for all platforms'
        required: false
        default: 'false'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install GitHub CLI
        run: |
          curl -sSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y || (curl -sSL https://github.com/cli/cli/releases/latest/download/gh_$(uname -s)_amd64.tar.gz | tar -xz && sudo cp gh_$(uname -s)_amd64/bin/gh /usr/local/bin/)

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.RFGITHUB_CLI_TOKEN }}" | gh auth login --with-token

      - name: Dispatch Linux build
        if: github.event.inputs.build-for-linux == 'true' || github.event.inputs.build-for-all == 'true'
        run: gh workflow run build-for-linux.yml --ref ${{ github.ref }}

      - name: Dispatch Windows build
        if: github.event.inputs.build-for-windows == 'true' || github.event.inputs.build-for-all == 'true'
        run: gh workflow run build-for-windows.yml --ref ${{ github.ref }}

      - name: Dispatch macOS build
        if: github.event.inputs.build-for-macos == 'true' || github.event.inputs.build-for-all == 'true'
        run: gh workflow run build-for-macos.yml --ref ${{ github.ref }}
