name: Build Dispatcher

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build-windows:
        description: "Trigger Windows build"
        required: false
        default: "false"
      build-linux:
        description: "Trigger Linux build"
        required: false
        default: "false"
      build-macos:
        description: "Trigger macOS build"
        required: false
        default: "false"
      build-all:
        description: "Trigger all builds"
        required: false
        default: "false"

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Dispatch Windows Build
        if: github.event.inputs.build-windows == 'true' || github.event.inputs.build-all == 'true'
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.NEWTOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-windows.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Dispatch Linux Build
        if: github.event.inputs.build-linux == 'true' || github.event.inputs.build-all == 'true'
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.NEWTOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-linux.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Dispatch macOS Build
        if: github.event.inputs.build-macos == 'true' || github.event.inputs.build-all == 'true'
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.NEWTOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-macos.yml/dispatches \
          -d '{"ref":"main"}'
