name: Build RealFire Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk patchelf libfuse2
          pip install customtkinter pyinstaller pillow requests

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile main.py --icon=/home/runner/work/RealFire-Installer/RealFire-Installer/assets/icons/firefox.ico --add-data "/home/runner/work/RealFire-Installer/RealFire-Installer/data/installer_data.json:data" --add-data "/home/runner/work/RealFire-Installer/RealFire-Installer/assets/icons:assets/icons" --add-data "/home/runner/work/RealFire-Installer/RealFire-Installer/assets/backgrounds:assets/backgrounds" --hidden-import='PIL._tkinter_finder'

      - name: Package into AppImage
        run: |
          mkdir -p RealFire-Installer.AppDir/usr/bin
          cp /home/runner/work/RealFire-Installer/RealFire-Installer/dist/main RealFire-Installer.AppDir/usr/bin/
          cp /home/runner/work/RealFire-Installer/RealFire-Installer/assets/icons/firefox.png RealFire-Installer.AppDir/
          
          cat << 'EOF' > RealFire-Installer.AppDir/AppRun
          #!/bin/bash
          SELF=$(readlink -f "$0")
          HERE=${SELF%/*}
          EXEC="${HERE}/usr/bin/start_app.sh"
          exec "${EXEC}"
          EOF
          
          chmod +x RealFire-Installer.AppDir/AppRun

    
          cat << 'EOF' > RealFire-Installer.AppDir/RealFire.desktop
          [Desktop Entry]
          Type=Application
          Name=RealFire Installer
          Exec=start_app.sh
          Icon=firefox
          Comment=RealFire Installer
          Categories=Utility;
          EOF

          chmod +x RealFire-Installer.AppDir/RealFire.desktop
          
          cat << 'EOF' > RealFire-Installer.AppDir/usr/bin/start_app.sh
          #!/bin/bash
          APPIMAGE_DIR=$(dirname "$(realpath "$0")")
          APP_EXECUTABLE="${APPIMAGE_DIR}/main"
          if [ ! -f "$APP_EXECUTABLE" ]; then
              echo "Error: App executable not found: $APP_EXECUTABLE"
              exit 1
          fi
          env DISPLAY="$DISPLAY" XAUTHORITY="$XAUTHORITY" "$APP_EXECUTABLE" "$@"
          EOF
          
          chmod +x RealFire-Installer.AppDir/usr/bin/start_app.sh
          
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x ./appimagetool-x86_64.AppImage
          ARCH=x86_64 ./appimagetool-x86_64.AppImage RealFire-Installer.AppDir RealFire-Installer.AppImage
        shell: bash

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NEWTOKEN }}
        with:
          tag_name: v1.0.0
          release_name: RealFire Installer v1.0.0
          body: |
            This is the first release of RealFire Installer.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NEWTOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./RealFire-Installer.AppImage
          asset_name: RealFire-Installer.AppImage
          asset_content_type: application/x-iso9660-appimage
