name: Dispatch Build Jobs

on:
  workflow_dispatch:
    inputs:
      build-for-windows:
        description: 'Build for Windows'
        required: false
        default: 'false'
      build-for-linux:
        description: 'Build for Linux'
        required: false
        default: 'false'
      build-for-macos:
        description: 'Build for macOS'
        required: false
        default: 'false'
      build-for-all:
        description: 'Build for all platforms'
        required: false
        default: 'false'

jobs:
  dispatch-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Windows build
        if: github.event.inputs.build-for-windows == 'true' || github.event.inputs.build-for-all == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-for-windows.yml',
              ref: context.ref,
            })

      - name: Trigger Linux build
        if: github.event.inputs.build-for-linux == 'true' || github.event.inputs.build-for-all == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-for-linux.yml',
              ref: context.ref,
            })

      - name: Trigger macOS build
        if: github.event.inputs.build-for-macos == 'true' || github.event.inputs.build-for-all == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-for-macos.yml',
              ref: context.ref,
            })
